### ISSUE TITLE
handle unable to DM a user.

### ISSUE THREAD

**Issue by squirrelo** [squirrelo/MovieNightBot#1]
properly handle the 403-forbbidden error when you can't DM a user that has their permissions locked down for DMs.

**Comment by squirrelo** [comment]
File "/home/admin/miniconda3/envs/movienightbot/lib/python3.7/site-packages/discord.py-1.3.1-py3.7.egg/discord/http.py", line 216, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50007): Cannot send messages to this user

**Comment by squirrelo** [comment]
now sends a message that reads `I can't DM you {username}!` but would be better to get channel messaged once that wont be so spammy

**Comment by itsTheFae** [comment]
Would require a bit of a refactor, but could be done if the actions return their message and destination rather than sending on their own.  

We could try returning the object to call `.send()` on and a tuple of options to be passed to it.  
Something like this in the actions:
`return (msg.author, (content=None, embed=embed_data))`  

The actual send and any error handling could be done in the base class, allowing for messages into the calling channel in the cases where DMs fail.

**Comment by itsTheFae** [comment]
@squirrelo what do you think of the proposed refactor?
